<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
<form action="<?php echo $this->getActionUrl() ?>" id="DimoMalchev" method="post">
    <ul class="form-list">
        <li>
            <div class="field">
                <label for="name" class="required"><em>*</em><?php echo Mage::helper('softuni_dimomalchev')->__('Name') ?>: </label>
                <div class="input-box">
                    <input type="text" id="name" class="input-text required-entry" name="name" />
                </div>
            </div>
        </li>
        <li>
            <div class="field">
                <label for="phone" class="required"><em>*</em><?php echo Mage::helper('softuni_dimomalchev')->__('Phone') ?>: </label>
                <div class="input-box">
                    <input type="text" id="phone" class="input-text required-entry" name="phone" />
                </div>
            </div>
        </li>
        <li>
            <div class="field">
                <label for="age" class="required"><em>*</em><?php echo Mage::helper('softuni_dimomalchev')->__('Age') ?>: </label>
                <div class="input-box">
                    <input type="text" id="age" class="input-text required-entry validate-number validate-number-range number-range-0-120" name="age" />
                </div>
            </div>
        </li>
        <li>
            <div class="field">
                <label for="email" class="required"><em>*</em><?php echo Mage::helper('softuni_dimomalchev')->__('E-mail') ?>: </label>
                <div class="input-box">
                    <input type="text" id="email" class="input-text required-entry validate-email" name="email" />
                </div>
            </div>
        </li>
        <li>
            <button type="submit" class="button"><span><?php echo Mage::helper('softuni_dimomalchev')->__('Submit') ?></span></button>
        </li>
    </ul>
</form>
<script type="text/javascript">
//<![CDATA[
    var contactForm = new VarienForm('DimoMalchev', true);
//]]>
</script>